visiblity 관련 유틸 함수 추가
ridi/rbhelper-android pull request #16
Opened 2019-12-10 00:51 UTC by JSpiner

## 개요
View의 visiblity 관련 간단한 유틸 함수를 추가해봤습니다.

## 사용 예
```kotlin
// 기존
if(view.visibility == View.INVISIBLE) {
    view.visibility = View.VISIBLE
}

// 적용 후
if(view.isInvisible()) {
    view.visible()
}
```

## 기타
- 반영된 후에 Ridibooks-Android 프로젝트에 전체 반영하겠습니다.

2019-12-10 01:06 UTC, freekering reviewed
`gone`, `invisible`, `visible`이 모두 형용사이기 때문에 상태를 조작하는 function의 단일 단어 이름으로는 어색한 것 같습니다.

2019-12-13 06:35 UTC, YSYoon requested changes
음 특별히 추가할 의견이 없어 reaction 만 남겼었는데요, 선국님께서 말씀하신대로 함수명의 변경이 필요한 것 같습니다

2019-12-13 06:42 UTC, JSpiner commented
문법을 지키자니 다른 단어가 필요해서 깔끔한 단어가 생각나지 않네요...
차라리 `show()` `hide()`의 다른 동사가 더 나을까요? 🤔

2019-12-13 06:51 UTC, YSYoon commented
> 문법을 지키자니 다른 단어가 필요해서 깔끔한 단어가 생각나지 않네요...
> 차라리 `show()` `hide()`의 다른 동사가 더 나을까요? 🤔

View API에서 VISIBLE / INVISIBLE / GONE 을 사용하고 있는데 저 이름들을 사용하지 않을 경우 직관적으로 View API 와 매칭시키기 어려워지기 때문에 show/hide 등은 별로 좋은 방향은 아닌 것 같습니다.

아쉬운대로 앞에 set 이나 make 등을 붙인다면 어떨까 싶긴 한데요, 다른 분들의 의견도 들어보면 좋을 것 같습니다.

2019-12-13 06:54 UTC, freekering commented
@YSYoon 님이 말씀하신 이유로.... 결국 원래 코드와 비슷한 형태가 될 가능성이 높고 그러면 결국 그냥 전후가 비슷할 것 같습니다 ㅋㅋ

2019-12-13 06:54 UTC, freekering commented
@JSpiner 님이 처음 이런게 있으면 좋겠다고 생각한 이유(?) 같은게 있으면 더 좋을 것 같네요.

2019-12-13 07:47 UTC, JSpiner commented
굉장히 자주 쓰이는 코드인데 꽤나 길어보여서 줄여보고자 했습니다

2019-12-13 10:52 UTC, namenu commented
지금 제안해주신 방향을 추상화해보면 이런 형태가 됩니다.

```kotlin
this.a = b; // 변경 전
this.b_fy(); // 변경 후
```

b라는 형용사를 보고 a를 추론할 수 있겠지만 일반적으로는 이런 생략이 바람직하지는 않은 것 같습니다.

글자 수가 줄어드는 것은 장점이긴 한데요, 이런 일반적인 패턴을 깨뜨릴 정도인지는 판단이 어렵네요. 🤔

2019-12-17 00:52 UTC, JSpiner commented
본래의도를 지키기가 어려워 close 합니다.

2019-12-17 00:52 UTC, closed without merging