unzipEncryptIfNeeded, unzipSelectedFile 추가
ridi/rbhelper-android pull request #7
Opened 2017-12-20 09:32 UTC by InyoungAum

Ridibooks-Android에서 압축을 푸는 동시에 encrypt를 해야하는 상황이 생겨서 함수를 추가했습니다. 

- **unzipEncryptIfNeeded** : 압축을 푸는 파일이 encryption이 필요하면 encrypt를 진행하고 결과에 따라 진행합니다. 성공, 실패, (암호화)불필요, 완료의 4가지 상태로 나누어져 있으며 완료상태의 경우 필요한 파일이 모두 encrypt가 완료된 후 불필요한 작업을 방지하기위해 추가했습니다. 

- **unzipSelectedFile** : 원하는 파일만 압축을 풀기위해 추가했습니다.

2017-12-21 10:02 UTC, freekering requested changes

2017-12-21 10:02 UTC, freekering commented on src/main/kotlin/com/ridi/books/helper/io/ZipHelper.kt
> +                    if (entry.name != selectedFileName) {
위의 if와 조합해보면 `if (selectedFileName?.equals(entry.name) == false)` 로 줄일 수 있지 않을까 싶네요.

2017-12-21 10:02 UTC, freekering commented on src/main/kotlin/com/ridi/books/helper/io/ZipHelper.kt
> +                    } else if (result == EncryptResult.FINISH) {
FINISH 라는 상태가 범용적이지 않은 느낌이 드는데 다른 접근 방법은 없을까요?

2017-12-21 10:47 UTC, InyoungAum commented
@freekering 코드리뷰 반영했습니다.

2017-12-21 13:51 UTC, namenu requested changes

2017-12-21 13:51 UTC, namenu commented on src/main/kotlin/com/ridi/books/helper/io/ZipHelper.kt
> +        fun onEncrypt(zipArchiveInputStream: ZipArchiveInputStream, outputStream: OutputStream, fileName: String): EncryptResult
`onEncrypt`는 콜백이 아니라 실제 명령이기 때문에 동사 형태인 `encrypt`가 적합하다고 생각합니다.

2017-12-21 13:51 UTC, namenu commented on src/main/kotlin/com/ridi/books/helper/io/ZipHelper.kt
> +                result = unzip(BufferedInputStream(FileInputStream(zipFile)),
원래도 그러했던 것으로 보입지만, 의미상 `any`가 맞지 않나요?

2017-12-21 13:51 UTC, namenu commented on src/main/kotlin/com/ridi/books/helper/io/ZipHelper.kt
> +                    if (result == EncryptResult.FAIL) {
반환코드를 사용하는 것보다는 "정상흐름"과 "예외"를 구분하는 것이 Java의 관행이라고 생각합니다. (그냥 의견)

2017-12-22 06:07 UTC, InyoungAum commented
@namenu 코드리뷰 반영했습니다.

2017-12-22 09:22 UTC, namenu requested changes

2017-12-22 09:22 UTC, namenu commented on src/main/kotlin/com/ridi/books/helper/io/ZipHelper.kt
> +                    if (isEncryptSuccess(result)) {
제가 말씀드렸던 것은 "예외 인스턴스를 던지는(throw )" 방법을 고려해보라는 뜻이었습니다.
변경하신 코드는 오히려 가독성이 떨어집니다.

2017-12-22 09:22 UTC, namenu commented on src/main/kotlin/com/ridi/books/helper/io/ZipHelper.kt
>                      val result = encryptor.onEncrypt(zipInputStream, out, file.name)
`onEncrypt`-> `encrypt` 변환이 되지 않았습니다.

2017-12-22 10:01 UTC, namenu approved these changes

2017-12-22 10:08 UTC, freekering requested changes

2017-12-22 10:08 UTC, freekering commented on src/main/kotlin/com/ridi/books/helper/io/ZipHelper.kt
> +                    if (result == EncryptResult.FAIL) {
여기 if 문 중첩이 좀 이상하게 된거 같은데요. 

근데 Exception 을 쓴다면 제가 이해한 방식은` EncryptResult` enum type을 없애고, `encrypt` 내에서 `EncryptFailedException` 혹은 `EncryptionUnnecessaryException` 등을 throw 하게끔 유도하는 방식이었습니다. 
지금 약간 다른 방식으로 이해된거 같은데요. 그런걸 차치하고서라도 일단 여기 if 구조는 매우 이상하네요.

2017-12-26 05:23 UTC, InyoungAum commented on src/main/kotlin/com/ridi/books/helper/io/ZipHelper.kt
> +                    if (result == EncryptResult.FAIL) {
`EncryptResult`를 없애긴 어려울 것 같습니다. if문 구조에 대해선 수정했습니다.

2017-12-26 07:55 UTC, InyoungAum commented
@freekering 리뷰 반영했습니다.

2017-12-27 10:09 UTC, freekering requested changes

2017-12-27 10:09 UTC, freekering commented on src/main/kotlin/com/ridi/books/helper/io/EncryptException.kt
> +open class EncryptException(message: String) : Exception(message)
Exception 들도 어차피 ZipHelper에 종속적인 애들이니 그 안으로 넣는게 어떨까요?
생각해보니 굳이 상위 클래스는 필요 없을거 같고 나머지 2개 이름도 각각 `EncyptionFailedException`, `EncryptionUnnecessaryException` 으로 형태를 맞추는게 좋을꺼 같은데 넘 길어질까요?

2017-12-28 01:44 UTC, InyoungAum commented on src/main/kotlin/com/ridi/books/helper/io/EncryptException.kt
> +open class EncryptException(message: String) : Exception(message)
기존 Exception중에 더 긴것이 있어서 괜찮을 것 같습니다. 리뷰 반영했습니다.

2017-12-28 03:47 UTC, freekering requested changes

2017-12-28 03:47 UTC, freekering commented on src/main/kotlin/com/ridi/books/helper/io/ZipHelper.kt
> +class EncryptionFailedException(fileName: String) : Exception("error while encrypt $fileName")
제 얘기는 `ZipHelper` class(object) 안에 있는게 어떨까 하는 거였습니다. `Encryption`과 `unzip`은 그냥 보기에는 아무런 관련이 없는 단어니까 `ZipHelper.Encryption~Exception` 이 되면 낫지 않을까 싶어서요. 너무 긴가 싶었던 것도 그래서고요.

2017-12-28 05:42 UTC, freekering approved these changes

2017-12-28 05:43 UTC, merged